### ISSUE TITLE
Giving 404 while submitting the form

### ISSUE THREAD

**Issue by rajatguptarg** [mishbahr/djangocms-forms#18] opened 2015-11-20 07:03 UTC
I creted a form using the documentation, but I didn't do any configuration steps. When I submit my form, its giving me 404.

`"POST /en/forms/submit/ HTTP/1.1" 404 3307"`

**Comment by mishbahr** [comment] 2015-11-20 09:49
I'm confused. What do you mean when you say:

> I didn't do any configuration steps

Did you add `djangocms_forms.urls` to your project's urls module or create a django CMS page to hook the application into (and publish the page).

Please provide more information.

Thanks

Mishbah

**Comment by rajatguptarg** [comment] 2015-11-20 09:59
yes

*Regards,*
*Rajat Gupta*Emailraja <rajatg@thoughtworks.com>t.gupta712@gmail.com
Telephone+91 9845741974 <+91+9845741974>

**Comment by rajatguptarg** [comment] 2015-11-20 10:00
Yes. I did that. But I didn't do any thing written under Configuration section in README.

**Comment by mishbahr** [comment] 2015-11-20 10:04
Hmm.. Settings in that sections are optional. 
Did you restart your server? 
Server restart is required to reload urls.

Mishbah

**Comment by rajatguptarg** [comment] 2015-11-20 10:30
yes... I did

**Comment by mishbahr** [comment] 2015-11-20 10:40
What version of django/django-cms are you using?

**Comment by rajatguptarg** [comment] 2015-11-20 10:41
1.7.10

**Comment by mishbahr** [comment] 2015-11-20 10:48
Just tested `djangocms-forms` with django (1.7.10) and django-cms (3.1.3)
I could't reproduce this issue. Sorry.

**Comment by mishbahr** [comment] 2015-12-05 17:33
I hope you resolved your issue. As I couldn't reproduce this issue.. I'll close this issue for now. 

If you have managed to resolve this issue.. please leave a comment on how you have fixed it. Thanks.

Mishbah

**Closed by mishbahr** 2015-12-05 17:33 UTC

**Comment by vindemasi** [comment] 2016-12-15 17:40
Hello,
I've experienced the same issue. As I've solved it I leave a comment here just
for documentation. The issue was happened when i put the url using i18n_patterns,
so a localized url is generated. Putting out of localized urls solves the issue.

Best regards

**Comment by zh0uquan** [comment] 2017-03-04 15:43
@vindemasi how exactly did u do it by meaning putting out of localized urls?

**Comment by vindemasi** [comment] 2017-03-04 15:53
@zh0uquan 

i was using something like:

urlpatterns = [
	...
]

urlpatterns += i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('djangocms_forms.urls')),
    url(r'^', include('cms.urls')),
)

and the error happens. The I've moved the forms urls like this:

urlpatterns = [
    ...
    url(r'^', include('djangocms_forms.urls')),
]

urlpatterns += i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('cms.urls')),
)

(note the forms.urls now is into urlspatterns  instead i18n_patterns.

This solved my issue.

**Comment by zh0uquan** [comment] 2017-03-04 15:59
@vindemasi  cool thanks!
